services:
    web-server:
        container_name: web-server
        build:
            dockerfile: ./Docker/httpd/Dockerfile
        ports:
            - "${FORWARD_SERVER_PORT:-8000}:80"
        volumes:
            - ./application:/var/www/html
    application:
        container_name: application
        build:
            dockerfile: ./Docker/php-fpm/Dockerfile
            target: development
        volumes:
            - ./Docker/php-fpm/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./application:/var/www/html
        env_file:
            - ./.env
            - ./Docker/.env
            - ./Docker/php-fpm/.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
    database:
        container_name: database
        image: mysql:8.4
        env_file:
            - ./.env
            - ./Docker/.env
            - ./Docker/mysql/.env
        ports:
            - "${FORWARD_MYSQL_PORT:-3306}:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        restart: unless-stopped
    cache:
        container_name: cache
        image: redis:7.4-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redisdata:/data
    adminer:
        container_name: adminer
        image: adminer:latest
        ports:
            - "${FORWARD_ADMINER_PORT:-8080}:8080"
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: "database:3306"
            ADMINER_PLUGINS: "dark-switcher"
        depends_on:
            - database

volumes:
    mysqldata:
    redisdata:
# 