services:
    web-server:
        container_name: web-server
        build:
            dockerfile: ./.docker/httpd/Dockerfile
        ports:
            - "${FORWARD_SERVER_PORT:-8000}:80"
        volumes:
            - ./application:/var/www/html
    application:
        container_name: application
        environment:
            MYSQL_HOST: "database"
            MYSQL_PORT: "3306"
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            REDIS_HOST: "cache"
            REDIS_PORT: "6379"
        build:
            dockerfile: ./.docker/php-fpm/Dockerfile
        volumes:
            - ./.docker/php-fpm/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./application:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
    database:
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        image: mysql:8.4
        ports:
            - "${FORWARD_MYSQL_PORT:-3306}:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        restart: unless-stopped
        command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    cache:
        container_name: cache
        image: redis:7.4-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redisdata:/data
    adminer:
        container_name: adminer
        environment:
            ADMINER_DEFAULT_SERVER: "database:3306"
            ADMINER_DEFAULT_USER: ${MYSQL_USER}
            ADMINER_DEFAULT_DATABASE: ${MYSQL_DATABASE}
            ADMINER_PLUGINS: ${ADMINER_PLUGINS:-dark-switcher}
        image: adminer:latest
        ports:
            - "${FORWARD_ADMINER_PORT:-8080}:8080"
        restart: unless-stopped
        depends_on:
            - database

volumes:
    mysqldata:
    redisdata:
